name: download-n-publish

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1 * *'
    

jobs:
  build:
    defaults:
      run:
        working-directory: ./src
        
    runs-on: ubuntu-latest    
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v .


    - name: run
      run: ./cloudvulndb-to-csv

    - name: git commit
      run: |
        git config --local user.email "actionRunner@github.com"
        git config --local user.name "github-actions"
        git add data/*.csv
        git commit -m "Added latest csv data"
        git push

